config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', registration: 'register' }

  namespace :admin do
    resources :dashboard,   only: %i(index)
    resources :users,       only: %i(index show)
    resources :categories,  only: %i(index destroy edit update new create)
    resources :products,    only: %i(index destroy edit update new create)
    resources :orders,      only: %i(index)
  end
  resources :home,             only: %i(index)
  resources :carts,            only: %i(index)
  resources :categories,       only: %i(show)
  resources :products,         only: %i(index show)
  resources :cart_items,       only: %i(create update destroy)
  resources :orders,           only: %i(new create)
  resources :users,            only: %i(show update)
  resources :addresses,        only: %i(new create edit update)
  get "*path", to: "application#page_404"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  VALID_PHONE_REGEX = /([+]84|0)([3|5|7|8|9])+([0-9]{8})\b/
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
end

app/models/asset.rb
class Asset < ApplicationRecord; end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :products, through: :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart, dependent: :destroy

  scope :latest, -> { order('cart_items.created_at DESC') }
end

app/models/category.rb
class Category < ApplicationRecord
  acts_as_paranoid

  has_many :products, dependent: :destroy

  validates :name, presence: true
end

app/models/coupon.rb
class Coupon < ApplicationRecord;end

app/models/delivery_address.rb
class DeliveryAddress < ApplicationRecord
  belongs_to :user
  has_many :orders

  validates :name, :phone, :address, presence: true
  validates :phone, format: { with: VALID_PHONE_REGEX }
end

app/models/order.rb
class Order < ApplicationRecord
  extend Enumerize

  has_many :order_items
  belongs_to :user
  belongs_to :delivery_address

  enumerize :payment_method, in: { cash: 0, card: 1 }
  enumerize :status, in: { pending: 0, active: 1, success: 2, reject: 3 }
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :cart_items
  has_many :order_items
  has_many :images

  acts_as_paranoid
  mount_uploader :image, PictureUploader

  validates :name, :image, :price, :residual,  presence: true

  scope :product_residual, -> { where("residual > ?", 0) }
  scope :oldest, -> { order('created_at ASC') }
end

app/models/recently_product.rb
class RecentlyProduct < ApplicationRecord;end

app/models/user.rb
class User < ApplicationRecord
  extend Enumerize

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  enum role:   { admin: 1, user: 0 }
  enumerize :gender, in: { male: true, female: false }

  mount_uploader :avatar, PictureUploader

  has_one  :cart
  has_many :delivery_addresses
  has_many :orders

  validates :name, :email, :phone, :gender, presence: true
  validates :email, format: { with: VALID_EMAIL_REGEX }
  validates :phone, format: { with: VALID_PHONE_REGEX }
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  def new
    @q = Product.ransack(params[:q])
    @address = DeliveryAddress.new
    @current_cart = current_user.cart
  end

  def create
    @q = Product.ransack(params[:q])
    @address = current_user.delivery_addresses.new(address_params)
    if @address.save
      redirect_to current_user
      flash[:notice] = "Create address success!"
    else
      render :new
    end
  end

  def edit
    @q = Product.ransack(params[:q])
    @address = current_user.delivery_addresses.find(params[:id])
  end

  def update
    @q = Product.ransack(params[:q])
    @address = current_user.delivery_addresses.find(params[:id])
    if @address.update(address_params)
      redirect_to current_user
      flash[:notice] = "Update address success!"
    else
      render :edit
    end
  end

  private

  def address_params
    params.require(:delivery_address).permit(:name, :phone, :address)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def index
    @q = Product.ransack(params[:q])
    @current_cart = current_user.cart
    @cart_items = @current_cart.nil? ? nil : @current_cart.cart_items.includes(:product).latest
    @total_payment = total_payment
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @categories = Category.all
    @q = Product.ransack(params[:q])
    @products = @q.result.page(params[:page]).per(12).product_residual
    if current_user.present?
      @current_cart = current_user.cart
    else
      @current_cart = Cart.new
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def new
    @q                = Product.ransack(params[:q])
    @order_items      = current_user.cart.cart_items.includes(:product).latest
    @total_price      = total_payment
    @current_cart     = current_user.cart
    @delivery_address = current_user.delivery_addresses.find_by(address: params[:address])

    respond_to do |format|
      format.html
      format.json do
        render json: {address: @delivery_address}
      end
    end
  end

  def create
    @cart_items = current_user.cart.cart_items
    generates_order
    if params[:payment_method] == 'card'
      generates_charge
      @order.update(status: 1)
    end
  end

  private

  def generates_order
    address = current_user.delivery_addresses.find_by(address: params[:address])
    if address
      @order = current_user.orders.create(
        shipping_fee:         params[:shipping_fee].to_f,
        total_payment:        params[:total_payment].to_f,
        payment_method:       params[:payment_method],
        delivery_address_id:  address.id,
        cart_id:              current_user.cart.id,
        status:               0
      )
      @cart_items.map do |cart_item|
        @order.order_items.create!(
          price_pay:   cart_item.product.price,
          quantity:    cart_item.quantity,
          total_price: cart_item.total_price,
          product_id:  cart_item.product.id
        )
      end
      CartItem.where(cart_id: current_user.cart.id).delete_all

      redirect_to root_path
      flash[:notice] = 'Order success!'
    else
      @q                = Product.ransack(params[:q])
      @order_items      = current_user.cart.cart_items.includes(:product).latest
      flash[:alert] = "Address can't not empty"
      render :new
    end
    
  end

  def generates_charge
    token = params[:stripeToken]
    customer = Stripe::Customer.create(
      email:  current_user.email,
      source: token
    )
    
    amount = total_payment

    charge = Stripe::Charge.create(
      amount:      amount.to_i,
      customer:    customer.id,
      currency:    'vnd',
      description: 'Rails Stripe customer'
    )
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @q = Product.ransack(params[:q])
    @products = @q.result.page(params[:page]).per(12).product_residual

    @current_cart = current_user&.cart
  end

  def show
    @q = Product.ransack(params[:q])
    @product = Product.find(params[:id])

    @current_cart = current_user&.cart
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @q            = Product.ransack(params[:q])
    @address      = current_user.delivery_addresses
    @current_cart = current_user.cart
  end

  def update
    if current_user.update(user_params)
      redirect_to user_path(current_user)
      flash[:notice] = "Update profile success!"
    else
      @q       = Product.ransack(params[:q])
      @address = current_user.delivery_addresses
      render :show
    end
  end

  private

  def user_params
    params.require(:user).permit(:avatar, :email, :name, :image, :phone, :gender)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "Apple Store"
    page_title.blank? ? base_title : page_title + " | " + base_title
  end

  def admin_page_title(title)
    if title
      title
    end
  end

  def format_number_to_currency number
    number_to_currency(number, unit: '', delimiter: '.' , precision: 0)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def option_for_address
    current_user.delivery_addresses.map do |item|
      item.address
    end
  end
end

app/views/layouts/admin/_footer.html.erb
<footer class="footer text-center">
  <p>Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights by Luan Dang</p>
</footer>

app/views/layouts/admin/_header.html.erb
<header class="topbar" data-navbarbg="skin5">
  <nav class="navbar top-navbar navbar-expand-md navbar-dark">
    <div class="navbar-header" data-logobg="skin6">
      <%= link_to root_path, class: "navbar-brand" do %>
        <span class="logo-text">
          <%= image_tag("logo-text-2") %>
        </span>
      <% end %>
      </a>
      <a class="nav-toggler waves-effect waves-light text-dark d-block d-md-none" href="javascript:void(0)"><i class="ti-menu ti-close"></i></a>
    </div>
    <div class="navbar-collapse collapse" id="navbarSupportedContent" data-navbarbg="skin5">
      <ul class="navbar-nav d-none d-md-block d-lg-none">
        <li class="nav-item">
          <a class="nav-toggler nav-link waves-effect waves-light text-white" href="javascript:void(0)"><i class="ti-menu ti-close"></i></a>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto d-flex align-items-center">
        <li class=" in">
          <form role="search" class="app-search d-none d-md-block me-3">
            <input type="text" placeholder="Search..." class="form-control mt-0">
            <a href="" class="active">
              <i class="fa fa-search"></i>
            </a>
          </form>
        </li>
        <li>
          <a class="profile-pic" href="#"><%= image_tag("varun.jpg", alt: "user-img", width: "36", class: "img-circle")%>
          <span class="text-white font-medium">Steave</span></a>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/admin/_sidebar.html.erb
<aside class="left-sidebar" data-sidebarbg="skin6">
  <div class="scroll-sidebar">
    <nav class="sidebar-nav">
      <ul id="sidebarnav">
        <li class="sidebar-item pt-2">
          <%= link_to admin_dashboard_index_path, class: "sidebar-link waves-effect waves-dark sidebar-link" do %>
            <i class="far fa-clock"></i>
            <span class="hide-menu">Dashboard</span>
          <% end %>
        </li>
        <li class="sidebar-item">
          <%= link_to admin_users_path, class: "sidebar-link waves-effect waves-dark sidebar-link" do %>
            <i class="fa fa-user"></i>
            <span class="hide-menu">User</span>
          <% end %>
        </li>
        <li class="sidebar-item">
          <%= link_to admin_orders_path, class: "sidebar-link waves-effect waves-dark sidebar-link" do %>
            <i class="fa fa-table"></i>
            <span class="hide-menu">Order</span>
          <% end %>
        </li>
        <li class="sidebar-item">
          <%= link_to admin_products_path, class: "sidebar-link waves-effect waves-dark sidebar-link" do %>
            <i class="fab fa-product-hunt"></i>
            <span class="hide-menu">Product</span>
          <% end %>
        </li>
        <li class="sidebar-item">
          <%= link_to admin_categories_path, class: "sidebar-link waves-effect waves-dark sidebar-link" do %>
            <i class="fas fa-list"></i>
            <span class="hide-menu">Category</span>
          <% end %>
        </li>
      </ul>
    </nav>
  </div>
</aside>

app/views/layouts/admin/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="preloader">
      <div class="lds-ripple">
        <div class="lds-pos"></div>
        <div class="lds-pos"></div>
      </div>
    </div>
    <div id="main-wrapper" data-layout="vertical" data-navbarbg="skin5" data-sidebartype="full" data-sidebar-position="absolute" data-header-position="absolute" data-boxed-layout="full">
      <%= render "layouts/admin/header" %>
      <%= render "layouts/admin/sidebar" %>
      <div class="page-wrapper" style="min-height: 250px;">
        <div class="page-breadcrumb bg-white">
          <div class="row align-items-center">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
              <h4 class="page-title"><%= admin_page_title(yield(:title)) %></h4>
            </div>
          </div>
        </div>
        <div class="container-fluid">
        <% flash.each do |message_type, message| %>
          <div class="flash-alert text-center alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
          <%= yield %>
        </div>
        <%= render "layouts/admin/footer" %>
      </div>
    </div>
  </body>
</html>

app/views/share/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error-explanation">
    <div class="alert alert-danger">
      <%= t "error.contains" %> <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/share/_modal.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Notify</h5>
      </div>
      <div class="modal-body">
        Item has been <span style="color: #dc3545;">Added</span> to your shopping cart
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-success" data-bs-dismiss="modal">Ok</button>
      </div>
    </div>
  </div>
</div>

app/views/share/_product.html.erb
<div class="col-xl-3 col-lg-3 col-md-6 col-sm-6">
  <div class="single-new-arrival mb-50 text-center">
    <div class="popular-img">
      <% if product.image? %>
        <%= image_tag product.image.url %>
      <% else %>
        <%= image_tag "apple_logo_grey.svg.png" %>
      <% end %>
      <input type="hidden" class="product-quatity" value="1">
      <div class="favorit-items btn-add-to-cart" data-bs-toggle="modal" data-bs-target="#exampleModal" data-product-id="<%= product.id %>">
        <%= image_tag("favorit-card") %>
      </div>
    </div>
    <div class="popular-caption">
      <p><%= link_to product.name, product_path(product), class: "text-decoration-none" %></p>
      <p><%= format_number_to_currency product.price %>đ</p>
      <p>Sold: <%= product.sold %></p>
      <button type="button" class="btn btn-outline-success">Buy now</button>
    </div>
  </div>
</div>
<%= render "share/modal" if current_user.present? %>