config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', registration: 'register' }

  namespace :admin do
    resources :dashboard,   only: %i(index)
    resources :users,       only: %i(index show)
    resources :categories,  only: %i(index destroy edit update new create)
    resources :products,    only: %i(index destroy edit update new create)
    resources :orders,      only: %i(index)
  end
  resources :home,             only: %i(index)
  resources :carts,            only: %i(index)
  resources :categories,       only: %i(show)
  resources :products,         only: %i(index show)
  resources :cart_items,       only: %i(create update destroy)
  resources :orders,           only: %i(new create)
  resources :users,            only: %i(show update)
  resources :addresses,        only: %i(new create edit update)
  get "*path", to: "application#page_404"
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :products, through: :cart_items
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def index
    @q = Product.ransack(params[:q])
    @current_cart = current_user.cart
    @cart_items = @current_cart.nil? ? nil : @current_cart.cart_items.includes(:product).latest
    @total_payment = total_payment
  end
end

app/views/carts/index.html.erb
<div class="container bg-white rounded-top mt-5 cart-layout" id="zero-pad">
  <div class="pt-4 text-center">
    <h3>Shopping Cart</h3>
  </div>
  <div class="row d-flex justify-content-center min-height-700">
    <div class="col-lg-10 col-12 pt-3 cart-items">
      <div class="d-flex pt-4">
      <div class="font-weight-normal size-cart">
        <%= @cart_items&.size || 0 %> items</div>
      </div>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Products</th>
            <th scope="col">Unit Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Total price</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody class="cart-item-container min-height-500">
          <%= render partial: "cart_items/cart_item", collection: @cart_items %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<div class="container bg-light rounded-bottom py-4 pay-cart" id="zero-pad">
  <div class="row d-flex justify-content-center">
    <div class="col-lg-10 col-12">
      <div class="d-flex justify-content-between align-items-center">
        <div>
          <%= link_to root_path do %>
            <button class="btn btn-sm bg-light border border-dark">Continue Shopping</button>
          <% end %>
        </div>
        <div class="px-md-0 px-1" id="footer-font">
          <b class="pl-md-4">
            Total:
            <span class="pl-md-4 total-payment" data-cart-id="<%= @current_cart&.id %>"><%= format_number_to_currency @total_payment %> đ</span>
          </b>
        </div>
        <div>
          <% if @cart_items.present? %>
            <%= link_to new_order_path do %>
              <button class="btn btn-sm bg-dark text-white px-lg-5 px-3 checkout-order">Checkout</button>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>