config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', registration: 'register' }

  namespace :admin do
    resources :dashboard,   only: %i(index)
    resources :users,       only: %i(index show)
    resources :categories,  only: %i(index destroy edit update new create)
    resources :products,    only: %i(index destroy edit update new create)
    resources :orders,      only: %i(index)
  end
  resources :home,             only: %i(index)
  resources :carts,            only: %i(index)
  resources :categories,       only: %i(show)
  resources :products,         only: %i(index show)
  resources :cart_items,       only: %i(create update destroy)
  resources :orders,           only: %i(new create)
  resources :users,            only: %i(show update)
  resources :addresses,        only: %i(new create edit update)
  get "*path", to: "application#page_404"
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :cart_items
  has_many :order_items
  has_many :images

  acts_as_paranoid
  mount_uploader :image, PictureUploader

  validates :name, :image, :price, :residual,  presence: true

  scope :product_residual, -> { where("residual > ?", 0) }
  scope :oldest, -> { order('created_at ASC') }
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  def index
    @q = Product.includes(:category).ransack(params[:q])
    @products = @q.result.page(params[:page]).per(15).oldest
    @category = Category.all
  end

  def new
    @product = Product.new
    @category = Category.all
  end

  def create
    @product = Product.new(product_params)
    @product.category_id = params[:category_id]
    @product.sold = 0
    if @product.save
      redirect_to admin_products_path
      flash[:success] = "Create product success!"
    else
      @category = Category.all
      render :new
    end
  end

  def destroy
    Product.find(params[:id]).destroy
    @q = Product.ransack(params[:q])
    @products = @q.result.page(params[:page]).per(15)
  end

  def edit
    @product = Product.find(params[:id])
    @category = Category.all
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:success] = "Update success!"
      redirect_to admin_products_path
    else
      @category = Category.all
      render :edit
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :image, :price, :residual, :description)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @q = Product.ransack(params[:q])
    @products = @q.result.page(params[:page]).per(12).product_residual

    @current_cart = current_user&.cart
  end

  def show
    @q = Product.ransack(params[:q])
    @product = Product.find(params[:id])

    @current_cart = current_user&.cart
  end
end

app/views/admin/products/_product.html.erb
<tr>
  <td><%= product.id %></td>
  <td class="product-image">
    <%= image_tag product.image.url if product.image? %>
  <td>
    <%= link_to edit_admin_product_path(product.id), class: "user-name" do %>
      <%= product.name %>
    <% end %>
  </td>
  <td><%= format_number_to_currency product.price %> đ</td>
  <td><%= product.residual %></td>
  <td><%= product.sold %></td>
  <td><%= product.category.name %></td>
  <td>
    <div class="delete-product" data-product-id="<%= product.id %>">
      <%= image_tag "icons-delete-25"  %>
    </div>
  </td>
  <td>
    <div class="close update-poduct" data-product-id="<%= product.id %>">
      <%= link_to edit_admin_product_path(product) do %>
        <%= image_tag "icons-pen-35" %>
      <% end %>
    </div>
  </td>
</tr>

app/views/admin/products/destroy.js.erb
$(".admin-product").html("<%= escape_javascript(render partial: "admin/products/product", collection: @products) %>");

app/views/admin/products/edit.html.erb
<% provide :title, "Update Product" %>
<div class="row">
  <div class="col-sm-12">
    <div class="white-box">
      <div class="table-responsive">
        <%= form_for @product, url: admin_product_path do |f| %>
          <%= render 'share/error_messages', object:  f.object %>
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
          <div class="picture my-3">
            <%= f.file_field :image, accept: "image/jpeg, image/gif, image/png, image/jpg" %>
          </div>
          <%= f.label :price %>
          <%= f.text_field :price, class: "form-control" %>
          <%= f.label :quantity %>
          <%= f.text_field :residual, class: "form-control" %>
          <%= f.label :description %>
          <%= f.text_field :description, class: "form-control" %>
          <%= f.label :category %>
          <%= select_tag :category_id, options_from_collection_for_select(@category, "id", "name"), class: "form-select" %>
          <%= f.button :submit, class: "btn btn-primary mt-3" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/index.html.erb
<% provide :title, "Product" %>
<div class="row">
  <div class="col-sm-12">
    <div class="white-box">
      <%= button_to "New product", new_admin_product_path, method: :get, class: "btn btn-primary mb-3" %>
      <div class="row">
        <div class="col-2">
          <%= select_tag :category, options_from_collection_for_select(@category, "id", "name"), class: "form-select category-option" %>
        </div>
      </div>
      <div class="table-responsive">
        <table class="table text-nowrap">
          <thead>
            <tr>
              <th class="border-top-0">Id</th>
              <th class="border-top-0">Image</th>
              <th class="border-top-0">Name</th>
              <th class="border-top-0">Price</th>
              <th class="border-top-0">Residual</th>
              <th class="border-top-0">Sold</th>
              <th class="border-top-0">Category</th>
              <th class="border-top-0"></th>
              <th class="border-top-0">Action</th>
            </tr>
          </thead>
          <tbody class="admin-product">
            <%= render partial: "admin/products/product", collection: @products %>
          </tbody>
        </table>
        <div class="d-flex justify-content-center">
          <%= paginate @products, window: 2 %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/new.html.erb
<% provide :title, "New Product" %>
<div class="row">
  <div class="col-sm-12">
    <div class="white-box">
      <div class="table-responsive">
        <%= form_for @product, url: admin_products_path do |f| %>
          <%= render 'share/error_messages', object:  f.object %>
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
          <div class="picture my-3">
            <%= f.file_field :image, accept: "image/jpeg, image/gif, image/png, image/jpg" %>
          </div>
          <%= f.label :price %>
          <%= f.text_field :price, class: "form-control" %>
          <%= f.label :quantity %>
          <%= f.text_field :residual, class: "form-control" %>
          <%= f.label :description %>
          <%= f.text_field :description, class: "form-control" %>
          <%= f.label :category %>
          <%= select_tag :category_id, options_from_collection_for_select(@category, "id", "name"), class: "form-select" %>
          <%= f.button :submit, class: "btn btn-primary mt-3" %>
        <% end %>
      </div>
    </div>
  </div>
</div>